arb-dir: lib/src/ui/localization/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/src/ui/localization/generated
nullable-getter: false
required-resource-attributes: true
use-escaping: true
format: true
