name: settings_repository
description: Settings domain repository for Zeta.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  desktop_platform_api:
      path: ../desktop_platform_api
  equatable: ^2.1.0
  settings_client:
      path: ../settings_client

dev_dependencies:
  test: ^1.31.1
  very_good_analysis: ^10.3.0
